// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#include <Rcpp.h>

using namespace Rcpp;

// SNPHWE2
double SNPHWE2(int32_t obs_hets, int32_t obs_hom1, int32_t obs_hom2, uint32_t midp);
RcppExport SEXP HardyWeinberg_SNPHWE2(SEXP obs_hetsSEXP, SEXP obs_hom1SEXP, SEXP obs_hom2SEXP, SEXP midpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int32_t >::type obs_hets(obs_hetsSEXP);
    Rcpp::traits::input_parameter< int32_t >::type obs_hom1(obs_hom1SEXP);
    Rcpp::traits::input_parameter< int32_t >::type obs_hom2(obs_hom2SEXP);
    Rcpp::traits::input_parameter< uint32_t >::type midp(midpSEXP);
    rcpp_result_gen = Rcpp::wrap(SNPHWE2(obs_hets, obs_hom1, obs_hom2, midp));
    return rcpp_result_gen;
END_RCPP
}
// SNPHWEX
double SNPHWEX(int32_t female_hets, int32_t female_hom1, int32_t female_hom2, int32_t male1, int32_t male2, uint32_t midp);
RcppExport SEXP HardyWeinberg_SNPHWEX(SEXP female_hetsSEXP, SEXP female_hom1SEXP, SEXP female_hom2SEXP, SEXP male1SEXP, SEXP male2SEXP, SEXP midpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int32_t >::type female_hets(female_hetsSEXP);
    Rcpp::traits::input_parameter< int32_t >::type female_hom1(female_hom1SEXP);
    Rcpp::traits::input_parameter< int32_t >::type female_hom2(female_hom2SEXP);
    Rcpp::traits::input_parameter< int32_t >::type male1(male1SEXP);
    Rcpp::traits::input_parameter< int32_t >::type male2(male2SEXP);
    Rcpp::traits::input_parameter< uint32_t >::type midp(midpSEXP);
    rcpp_result_gen = Rcpp::wrap(SNPHWEX(female_hets, female_hom1, female_hom2, male1, male2, midp));
    return rcpp_result_gen;
END_RCPP
}
// support
NumericMatrix support();
RcppExport SEXP HardyWeinberg_support() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(support());
    return rcpp_result_gen;
END_RCPP
}

#include <R_ext/Rdynload.h>

static const
R_CallMethodDef callMethods[] = {
{"support", (DL_FUNC) &support, 0},  
{"SNPHWE2", (DL_FUNC) &SNPHWE2, 4},
{"SNPHWEX", (DL_FUNC) &SNPHWEX, 7},
NULL
};

void R_init_HardyWeinberg(DllInfo *info)
{
/* Register the .C and .Call routines.
No .Fortran() or .External() routines,
so pass those arrays as NULL.
*/
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}
