# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SNPHWE2 <- function(obs_hets, obs_hom1, obs_hom2, midp) {
    .Call('HardyWeinberg_SNPHWE2', PACKAGE = 'HardyWeinberg', obs_hets, obs_hom1, obs_hom2, midp)
}

SNPHWEX <- function(female_hets, female_hom1, female_hom2, male1, male2, midp) {
    .Call('HardyWeinberg_SNPHWEX', PACKAGE = 'HardyWeinberg', female_hets, female_hom1, female_hom2, male1, male2, midp)
}

support <- function() {
    .Call('HardyWeinberg_support', PACKAGE = 'HardyWeinberg')
}

